# reference: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: py-lambda-gh-actions
useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ${env:AWS_DEFAULT_REGION}
  timeout: 45
  logRetentionInDays: 90
  deploymentBucket:
    name: ${self:service}-${self:provider.stage}-serverlessdeploymentbucket


package:
  patterns:
  - '!.github/**'
  - '!requirements.txt'
  - '!README.md'
  - '!gh-actions-aws-iam.json'
  - '!LICENSE'

functions:
  helloworld:
    handler: src.handler.lambda_handler
    description: AWS Lambda function to test GitHub Actions
    maximumRetryAttempts: 0
    events:
      - schedule:
          description: Calls AWS Lambda function every hour
          rate: cron(0 */1 * * ? *)

plugins:
  - serverless-layers
  - serverless-deployment-bucket
custom:
  serverless-layers:
    dependenciesPath: ./requirements.txt
    compatibleRuntimes:
      - python3.8
  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
