name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Setup AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Install Serverless CLI
        run: |
          curl -o- -L https://slss.io/install | bash
          echo "$HOME/.serverless/bin" >> $GITHUB_PATH
      - name: Install npm packages
        run: npm i
      - name: Deploy
        run: sls deploy --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
